// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Script} from "forge-std/Script.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {console} from "forge-std/console.sol";
import {Merkle} from "murky/src/Merkle.sol";
import {ScriptHelper} from "murky/script/common/ScriptHelper.sol";

/**
 * @title MakeMerkle
 * @notice Reads the input JSON generated by GenerateInput.s.sol,
 *         builds the Merkle tree, and writes proofs + root to output.json.
 *
 * Usage:
 *   1. forge script script/GenerateInput.s.sol  → generates input.json
 *   2. forge script script/MakeMerkle.s.sol     → generates output.json
 *   3. Use the root from output.json when deploying MerkleClaim contract.
 *
 * Output → /script/target/output.json
 */
contract MakeMerkle is Script, ScriptHelper {
    using stdJson for string;

    Merkle private m = new Merkle();

    string private inputPath  = "/script/target/input.json";
    string private outputPath = "/script/target/output.json";

    string  private elements = vm.readFile(string.concat(vm.projectRoot(), inputPath));
    string[] private types   = elements.readStringArray(".types");
    uint256  private count   = elements.readUint(".count");

    bytes32[] private leafs   = new bytes32[](count);
    string[]  private inputs  = new string[](count);
    string[]  private outputs = new string[](count);

    string private output;

    // Returns the JSON path for a value at index i, field j
    // e.g. ".values.0.0" = address, ".values.0.1" = amount
    function getValuesByIndex(uint256 i, uint256 j) internal pure returns (string memory) {
        return string.concat(".values.", vm.toString(i), ".", vm.toString(j));
    }

    // Builds a single JSON entry for one claimant in the output file
    function generateJsonEntries(
        string memory _inputs,
        string memory _proof,
        string memory _root,
        string memory _leaf
    ) internal pure returns (string memory) {
        return string.concat(
            "{",
            "\"inputs\":", _inputs, ",",
            "\"proof\":",  _proof,  ",",
            "\"root\":\"", _root,   "\",",
            "\"leaf\":\"", _leaf,   "\"",
            "}"
        );
    }

    function run() public {
        console.log("Generating Merkle tree from %s", inputPath);

        // Build all leaf hashes
        for (uint256 i = 0; i < count; ++i) {
            string[] memory input = new string[](types.length);
            bytes32[] memory data = new bytes32[](types.length);

            for (uint256 j = 0; j < types.length; ++j) {
                if (compareStrings(types[j], "address")) {
                    address value = elements.readAddress(getValuesByIndex(i, j));
                    data[j]  = bytes32(uint256(uint160(value)));
                    input[j] = vm.toString(value);
                } else if (compareStrings(types[j], "uint")) {
                    uint256 value = vm.parseUint(elements.readString(getValuesByIndex(i, j)));
                    data[j]  = bytes32(value);
                    input[j] = vm.toString(value);
                }
            }

            // Double hash leaf to protect against preimage attacks
            leafs[i] = keccak256(bytes.concat(keccak256(ltrim64(abi.encode(data)))));
            inputs[i] = stringArrayToString(input);
        }

        // Generate proofs for each leaf
        for (uint256 i = 0; i < count; ++i) {
            string memory proof = bytes32ArrayToString(m.getProof(leafs, i));
            string memory root  = vm.toString(m.getRoot(leafs));
            string memory leaf  = vm.toString(leafs[i]);
            string memory input = inputs[i];

            outputs[i] = generateJsonEntries(input, proof, root, leaf);
        }

        output = stringArrayToArrayString(outputs);
        vm.writeFile(string.concat(vm.projectRoot(), outputPath), output);

        console.log("DONE: Merkle tree written to %s", outputPath);
        console.log("Use the root value when deploying MerkleClaim.sol");
    }
}
